;;; init-packages.el --- 必要なパッケージのインストール.
;;
;; -*- mode: Emacs-Lisp; coding: utf-8 -*-
;; Last updated: <2018/04/04 16:02:06>
;;

;;; Commentary:

;;; Code:

(require 'init-enhance (locate-user-emacs-file "init-enhance.el"))

;; リポジトリの設定
(e:add-package-repository "melpa-stable" "https://stable.melpa.org/packages/" 10)
(e:add-package-repository "melpa" "https://melpa.org/packages/")

;; パッケージ・設定の管理関連
(e:add-required-package 'use-package)
(e:add-required-package 'init-loader)

;; 各種パッケージ
(e:add-required-package 'ace-link)
(e:add-required-package 'ace-window)
(e:add-required-package 'all)
(e:add-required-package 'all-ext)
(e:add-required-package 'android-mode)
(e:add-required-package 'anzu)
(e:add-required-package 'atomic-chrome)
(e:add-required-package 'auto-save-buffers-enhanced)
(e:add-required-package 'auto-shell-command)
(e:add-required-package 'avy)
(e:add-required-package 'avy-migemo :if (executable-find "cmigemo"))
(e:add-required-package 'avy-zap)
(e:add-required-package 'bar-cursor)
(e:add-required-package 'bbyac)
(e:add-required-package 'cl-lib-highlight)
(e:add-required-package 'column-marker)
(e:add-required-package 'company)
(e:add-required-package 'company-irony)
(e:add-required-package 'company-irony-c-headers)
(e:add-required-package 'company-php)
(e:add-required-package 'company-web)
(e:add-required-package 'concurrent)
(e:add-required-package 'csv-mode)
(e:add-required-package 'ctags-update :if (executable-find "ctags"))
(e:add-required-package 'dash)
(e:add-required-package 'ddskk)
(e:add-required-package 'deferred)
(e:add-required-package 'dired+)
(e:add-required-package 'dired-atool :if (executable-find "atool"))
(e:add-required-package 'dired-collapse)
(e:add-required-package 'dired-filter)
(e:add-required-package 'dired-hacks-utils)
(e:add-required-package 'dired-narrow)
(e:add-required-package 'dired-ranger)
(e:add-required-package 'dired-sort)
(e:add-required-package 'dired-subtree)
(e:add-required-package 'dired-toggle-sudo)
(e:add-required-package 'dumb-jump)
(e:add-required-package 'edbi)
(e:add-required-package 'editorconfig)
(e:add-required-package 'eldoc-extension)
(e:add-required-package 'elscreen)
(e:add-required-package 'emmet-mode)
(e:add-required-package 'evil)
(e:add-required-package 'evil-numbers)
(e:add-required-package 'evil-surround)
(e:add-required-package 'exec-path-from-shell :if (not (os-type-win-p)))
(e:add-required-package 'expand-region)
(e:add-required-package 'f)
(e:add-required-package 'flx-ido)
(e:add-required-package 'flycheck)
(e:add-required-package 'flycheck-irony)
(e:add-required-package 'flycheck-swift)
(e:add-required-package 'free-keys)
(e:add-required-package 'git-gutter :if (not window-system))
(e:add-required-package 'git-gutter-fringe :if window-system)
(e:add-required-package 'gitattributes-mode)
(e:add-required-package 'gitconfig-mode)
(e:add-required-package 'gitignore-mode)
(e:add-required-package 'google-translate)
(e:add-required-package 'helm)
(e:add-required-package 'helm-ag :if (or (executable-find "rg")
                                         (executable-find "pt")))
(e:add-required-package 'helm-c-yasnippet)
(e:add-required-package 'helm-descbinds)
(e:add-required-package 'helm-dired-history)
(e:add-required-package 'helm-elscreen)
(e:add-required-package 'helm-flycheck)
(e:add-required-package 'helm-ghq :if (executable-find "ghq"))
(e:add-required-package 'helm-mode-manager)
(e:add-required-package 'helm-projectile)
(e:add-required-package 'helm-swoop)
(e:add-required-package 'highlight-symbol)
(e:add-required-package 'hydra)
(e:add-required-package 'ido-completing-read+)
(e:add-required-package 'ido-hacks)
(e:add-required-package 'ido-vertical-mode)
(e:add-required-package 'ido-yes-or-no)
(e:add-required-package 'irony)
(e:add-required-package 'irony-eldoc)
(e:add-required-package 'lacarte)
(e:add-required-package 'linum-relative)
(e:add-required-package 'list-processes+)
(e:add-required-package 'magit)
(e:add-required-package 'magit-gitflow)
(e:add-required-package 'menu-bar+)
(e:add-required-package 'migemo :if (executable-find "cmigemo"))
(e:add-required-package 'multiple-cursors)
(e:add-required-package 'mykie)
(e:add-required-package 'open-junk-file)
(e:add-required-package 'php-eldoc)
(e:add-required-package 'php-mode)
(e:add-required-package 'popwin)
(e:add-required-package 'powerline)
(e:add-required-package 'projectile)
(e:add-required-package 'psysh :if (executable-find "psysh"))
(e:add-required-package 'rainbow-mode)
(e:add-required-package 'recentf-ext)
(e:add-required-package 'restclient)
(e:add-required-package 'restclient-helm)
(e:add-required-package 's)
(e:add-required-package 'selected)
(e:add-required-package 'shell-pop)
(e:add-required-package 'smartparens)
(e:add-required-package 'string-edit)
(e:add-required-package 'sudo-edit)
(e:add-required-package 'swift-mode)
(e:add-required-package 'term+)
(e:add-required-package 'term+mux)
(e:add-required-package 'twittering-mode)
(e:add-required-package 'typescript-mode)
(e:add-required-package 'undo-tree)
(e:add-required-package 'undohist)
(e:add-required-package 'vimrc-mode)
(e:add-required-package 'visual-regexp)
(e:add-required-package 'volatile-highlights)
(e:add-required-package 'web-mode)
(e:add-required-package 'which-key)
(e:add-required-package 'windata)
(e:add-required-package 'yaml-mode)
(e:add-required-package 'yasnippet)

;; インストール実施
(e:install-required-packages)

(provide 'init-packages)
;;; init-packages.el ends here
